language: python

# cache:
#   directories:
#     - gecko
#   timeout: 1000

env:
  - DISPLAY=':99.0'

addons:
  apt:
    packages:
      - autoconf2.13
      - sshpass
      - p7zip-full

install:
  - pip install --upgrade pip
  - pip install -U mercurial
  - ./scripts/clone-gecko.sh

before_script:
  - ./scripts/build-firefox.sh
  - sh -e /etc/init.d/xvfb start

script:
  - echo $TRAVIS_COMMIT_RANGE
  - ./scripts/run-tests.sh $TRAVIS_COMMIT_RANGE
